//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterOfCreativity.BaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsSuccessful { get; set; }

        public string Successful
        {
            get
            {
                return IsSuccessful ? "Вход выполнен" : "Вход не выполнен";
            }
        }
    
        public virtual User User { get; set; }
    }
}
